# Generated by Django 4.1.6 on 2023-03-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobposition_profile_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
