# Generated by Django 4.1.6 on 2023-02-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_myuser_first_name_remove_myuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
