# Generated by Django 4.1.6 on 2023-03-22 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_group_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="owner",
        ),
    ]
