# Generated by Django 4.1.6 on 2023-03-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_group_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
