# Generated by Django 4.1.6 on 2023-03-24 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_remove_comment_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="product",
            new_name="group",
        ),
    ]
