# Generated by Django 4.1.6 on 2023-03-31 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("degree", models.CharField(max_length=25)),
                ("specialization", models.CharField(max_length=25)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="EmploymentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                ("company_name", models.CharField(max_length=25)),
                ("location", models.CharField(max_length=25)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.DateField()),
                (
                    "type_employment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resume.employmentcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("surname", models.CharField(max_length=25)),
                (
                    "photo",
                    models.ImageField(
                        default="default.png", upload_to="media/profile_image/"
                    ),
                ),
                ("phone", models.CharField(max_length=25)),
                ("position", models.CharField(max_length=25)),
                ("description", models.TextField()),
                ("education", models.ManyToManyField(to="resume.education")),
                ("experience", models.ManyToManyField(to="resume.experience")),
                ("languages", models.ManyToManyField(to="resume.language")),
                ("skills", models.ManyToManyField(to="resume.skill")),
            ],
        ),
    ]
