# Generated by Django 4.1.6 on 2023-03-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teamuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamuser',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_users', to='teams.team'),
        ),
    ]
